{   'active': True,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': [],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'visualize_queries',
    'qweb': [],
    'sequence': -1,
    'test': [],
    'version': '15.0.1.0'}
