{   'active': True,
    'application': False,
    'assets': {},
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': False,
    'conflicts': [],
    'css': [],
    'data': ['views/query_tree.xml', 'views/menu.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['base'],
    'installable': True,
    'js': [],
    'name': 'visualize_queries',
    'qweb': [],
    'test': [],
    'version': '15.0.1.0'}
